name: Workflow
on:
  push:
    branches:
      - feature/dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install ESLint dependencies (if needed)
        run: npm install --save-dev eslint @eslint/js

      - name: Run ESLint (auto fix)
        run: npx eslint . --ext .js,.ts --fix
      

  unit-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        id: unit-test
        run: npm test

      - name: Upload test results
        if: steps.unit-test.outcome == 'failure' || steps.unit-test.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: ./test-results.xml

  Code-Coverage:
    runs-on: self-hosted
    needs: [unit-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Run code coverage
        id: code-coverage
        run: npm run coverage

      - name: Upload code coverage results
        if: steps.code-coverage.outcome == 'failure' || steps.code-coverage.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-results
          path: ./coverage/lcov.info

  Scan-Secrets-with-Gitleaks:
    runs-on: self-hosted
    needs: [Code-Coverage]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.9
        with:
          config: .gitleaks.toml
          fail_on: all

  build-docker-image:
    runs-on: self-hosted
    needs: [Scan-Secrets-with-Gitleaks]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: msoliman427/solar-system:${{ github.sha }}
          build-args: |
            MONGO_URI=${{ secrets.MONGO_URI }}
            MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}
            MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
